name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx vitest run --reporter=json --outputFile=vitest-result.json
      - name: Generate summary
        run: |
          echo "## 🧪: Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Test | Duration (ms) |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|------|---------------|" >> $GITHUB_STEP_SUMMARY
          jq -r '.testResults[].assertionResults[]
            | "| " + (if .status == "passed" then "✅: Pass" else "❌: Fail" end)
            + " | " + .title
            + " | " + (.duration|tostring) + " |"' vitest-result.json >> $GITHUB_STEP_SUMMARY
  hello:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Olá"
